### ISSUE TITLE
[BUG] issue with day height in calendar mode

### ISSUE THREAD

**Issue by marksie1988** [marksie1988/atomic-calendar-revive#123]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  * Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  * Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

The calendar is larger with the new release, which causes issues with the view for some people

### Steps to Reproduce

1. update to 1.5.2

**Expected behavior**

Days are much larger than they used to be when no icon was used. 

**Actual behavior:**

**Screenshots**

![image](https://user-images.githubusercontent.com/159166/82835619-7b6cf580-9ebc-11ea-916a-16351ab41b4c.png)

**Card Configuration**

```yaml
type: custom:stack-in-card
cards:
  - type: markdown
    style: |
      ha-card { height: 40px; }
    padding: '0px'
    content: >
      ## {{ states('sensor.clocktalk_date') }}

  - type: "custom:atomic-calendar-revive"
    style: |
      ha-card { height: 215px; }
    title: ""
    firstDayOfWeek: 7
    defaultMode: 2
    showDate: false
    showLastCalendarWeek: false
    entities:
      - entity: calendar.holidays_in_united_states
        type: holiday
        blacklist: 'daylight, super, tax, black, monday'

  - type: markdown
    style: |
      ha-card { height: 185px }
    padding: '0px'
    content: >
      &nbsp;

      {{ states('sensor.next_payday') }}

      {{ states('sensor.next_holiday') }}

      {{ states('sensor.next_birthday') }}

      {{ states('sensor.next_fullmoon') }}

      {{ states('sensor.next_dst') }}
```

### Versions

* HomeAssistant Version: 110
* Plugin Version: 1.5.2
