### ISSUE TITLE
Event Icon colors not working as expected

### ISSUE THREAD

**Issue by kaizersoje** [marksie1988/atomic-calendar-revive#157]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

`CalEventIcon1Color` and `CalEventIcon2Color` not working as expected after upgrading to v1.8.5

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior**

`CalEventIcon1Color` and `CalEventIcon2Color` working as expected

**Actual behavior:**

**Screenshots**

**Card Configuration**

```
      - type: "custom:atomic-calendar-revive"
        name: "Home Calendar"
        entities:
        - entity: calendar.home_calendar
          type: icon2
        - entity: calendar.facebook_events
          type: icon1
        - entity: calendar.aus_vic_public_holidays
          type: holiday
        CalEventIcon1: mdi:facebook
        CalEventIcon1Color: LIGHTSKYBLUE
        CalEventIcon2Color: GOLDENROD
        CalEventHolidayColor: DEEPPINK
        enableModeChange: true
        defaultMode: 2
        fullDayEventText: 'All day'
        untilText: 'Until'
        showColors: true
        maxDaysToShow: 7
        showLocation: true
        showMonth: false
        showCurrentEventLine: false
        dateColor: PERU
        dateSize: 110
        timeColor: ANTIQUEWHITE
        # timeSize: 90
        titleColor: gold
        # titleSize: 100
        locationIconColor: AZURE
        locationLinkColor: GAINSBORO
        # locationTextSize: 90
        dimFinishedEvents: true
        finishedEventOpacity: 0.6
        # finishedEventFilter: 'grayscale(100%)'
        # dayWrapperLineColor: black
        # eventBarColor: blue
        showProgressBar: true
        # progressBarColor: blue
        nameColor: DARKKHAKI
        calWeekDayColor: "#b8490d"
        calDayColor: "rgb(179,222,120)"
        defaultCalColor: "rgb(255,0,0)"
        eventTitleColor: BURLYWOOD
        eventTitleSize: 115

```
```yaml

```

### Versions

- HomeAssistant Version: 0.110.2
- Plugin Version: 1.8.5
