### ISSUE TITLE
[BUG] Card does not refresh over time

### ISSUE THREAD

**Issue by Johmpa** [marksie1988/atomic-calendar-revive#158]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

The card state does not refresh over time. Events are not marked as completed, days do not go forward, progressbars do not progress, new events do not show up, no loading is performed etc. The only way to update is to refresh the entire page or navigate away from the dashboard. 

This worked fine on the original atomic-calendar implementation so something is amiss, although I cannot tell if it is my environment that is to blame. This has been observed on Chrome browser on multiple computers, all running Windows 10. 

### Steps to Reproduce

1. Create a card with a calendar
2. Show the lovelace dashboard with the card
3. Create an event in the calendar. The event will not show up by itself
4. Refresh the page and wait until the event starts. A progressbar will not appear
5. Wait until the event completes. It will not grey out. 

**Expected behavior**

New events should be loaded promptly, events should properly be shown as completed, days should reflect actual day by itself etc.

**Actual behavior:**

The lovelace card is effectively frozen in the state it loaded as until a refresh is forced. 

**Screenshots**

**Card Configuration**

```  
  - disableEventLink: true
    disableLocationLink: true
    entities:
      - entity: calendar.events
      - blacklist: 'Daily, Lunch, synk'
        entity: calendar.work
      - entity: calendar.personlig
      - entity: calendar.releasecalendar
      - entity: calendar.warhammer
      - entity: calendar.helgdagar_i_sverige
      - entity: calendar.vuxna_man_gor_saker_tillsammans
    language: sv
    maxDaysToShow: 1
    noEventsForNextDaysText: Ingenting kommande dagar
    noEventsForTodayText: Ingenting idag
    showColors: true
    showDate: true
    showFullDayProgress: true
    showLoader: true
    showLocation: false
    showNoEventsForToday: true
    showProgressBar: true
    showWeekDay: true
    sortByStartTime: true
    title: Kalender
    type: 'custom:atomic-calendar-revive'
```

### Versions

- HomeAssistant Version: 0.110.3
- Plugin Version: 1.8.3
