### ISSUE TITLE
Are locationLinkColor and locationIconColor being overridden by overall theme?

### ISSUE THREAD

**Issue by ha14937** [marksie1988/atomic-calendar-revive#173]
## Summary

**Expected behavior**
Unable to change the color of locationLinkColor or locationIconColor

**Actual behavior:**
I expect the location label to match the rgb specified

**Screenshots**
![image](https://user-images.githubusercontent.com/56581105/84454465-96639780-ac28-11ea-9b97-24bac3dd28e8.png)

**Card Configuration**

```yaml
dateSize: 90
dimFinishedEvents: true
entities:
  - entity: calendar.AAAAAAA_gmail_com
  - entity: calendar.BBBBBBBB_gmail_com
  - entity: calendar.holidays_in_united_states
dayWrapperLineColor: orange
dateColor: tan
eventBarColor: blue
eventTitleColor: tan
locationLinkColor: 'rgb(253, 253, 150)'
locationIconColor: 'rgb(253, 253, 150)'
progressBarColor: blue
showColors: true
timeColor: gray
eventTitleSize: 100
finishedEventFilter: grayscale(100%)
finishedEventOpacity: 0.6
fullDayEventText: All day
locationTextSize: 90
maxDaysToShow: 7
name: Calendar
showCurrentEventLine: false
showDate: true
showLocation: true
showMonth: true
showProgressBar: true
showWeekDay: true
timeSize: 90
untilText: Until
sortByStartTime: true
showDescription: true
showNoEventsForToday: true
type: 'custom:atomic-calendar-revive'
```

## Additional context

I am using Google Dark Theme By JuanMTech  - could that be interfering?

(...and thanks for reviving this card - I love it!)
