### ISSUE TITLE
Chosen ICONS are ignored 

### ISSUE THREAD

**Issue by BjornS98** [marksie1988/atomic-calendar-revive#178]
After update HA, the icons I have set up for the following calendars are ignored, and the standard (gift,home,star) is used. Somebody got an idea of how this is happening?

```
  - CalEventIcon1: 'mdi:account'
    CalEventIcon2: 'mdi:white-balance-sunny'
    CalEventIcon3: 'mdi:delete-empty'
    defaultMode: 2
    entities:
      - entity: calendar.calendar
        type: icon1
      - entity: calendar.feestdagen_in_belgie
        type: icon2
      - entity: calendar.afval
        type: icon3
    name: Calendar
    showNoEventsForToday: false
    showWeekDay: false
    sortByStartTime: false
    title: Calendar
    type: 'custom:atomic-calendar-revive'
    showColors: true
    showDate: false
```
