### ISSUE TITLE
No color on title events

### ISSUE THREAD

**Issue by kevinpagnat** [marksie1988/atomic-calendar-revive#212]
## Summary

I have configure this card with the help of the website and everything works fine so far.

**Expected behavior**

I use the 'Events' mode (not Calendar) and I put the "showColors: true" parameter in the card to have the titles of my different events, linked to different calendars, in different colors (colors retrieved from Google Calendar)

**Actual behavior:**

Every title has the same color (black)

**Card Configuration**

```yaml
dayWrapperLineColor: 'rgb(125, 125, 125)'
entities:
  - entity: calendar.agenda_perso
  - entity: calendar.contacts
fullDayEventText: 'All day'
showColors: true
showMonth: true
sortByStartTime: true
type: 'custom:atomic-calendar-revive'
untilText: jusqu'au
maxDaysToShow: 30
```
