### ISSUE TITLE
how to set title color in event view 

### ISSUE THREAD

**Issue by jo-me** [marksie1988/atomic-calendar-revive#227]
## Summary

I want to have different text colors in event view depending on the calendar the events originate from

**Expected behavior**

Text color based on color specified at calendar entity

**Actual behavior:**

Nothing

**Screenshots**

![image](https://user-images.githubusercontent.com/10351272/87921230-91d99c80-ca7a-11ea-8d1f-ec63cba57051.png)

**Card Configuration**

```
entities:
  - entity: calendar.gelber_sack_abholtermine
    titleColor: orange
  - entity: calendar.abfallwirtschaft_stuttgart
    titleColor: brown
maxDaysToShow: 7
showColors: true
showLoader: true
timeColor: darkgrey
title: Kalender
type: 'custom:atomic-calendar-revive'
name: Kalender

```

## Additional context

I'm migrating from the old atomic calendar to your component atm.
The old atomic calendar hat a titleColor attribute for each calendar entity.

According to docs and examples of your component:
- entities have a "color" option -> did not work in event view
- in quick start page the "titlecolor" setting is used => did not work

The global eventTitleColor setting works but is used for all events.

What is the right option?

Thanks
