### ISSUE TITLE
Progressbars are invisible

### ISSUE THREAD

**Issue by Johmpa** [marksie1988/atomic-calendar-revive#274]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

Since the update introducing relative times to event the progressbars have disappeared from my cards. I have attempted to run the cards with or without relative time as well as with fullDayProgress: false. 

Upon further examination I can see that the progressbar element is present, just not visible. See attached screenshot. 

### Steps to Reproduce

Try to use progressbars. 

**Expected behavior**

Visible progressbars

**Actual behavior:**

Invisible Progressbars

**Screenshots**

Current view with showProgressBar on. The Top event should have a progressbar with slightly less than 50% completion. 

<img width="844" alt="ProgressbarMissingResult" src="https://user-images.githubusercontent.com/1575874/90647953-39441d80-e239-11ea-843f-fff37faba844.png">

Inspection view of the page source. Note that the progressbar element appears to be present, but it is not visible. 
<img width="1056" alt="ProgressbarMissingInspect" src="https://user-images.githubusercontent.com/1575874/90648043-5842af80-e239-11ea-84f5-03257a071e95.png">

**Card Configuration**

```
disableEventLink: true
disableLocationLink: true
entities:
  - entity: calendar.personlig
  - entity: calendar.events
  # other calendars omitted
hideFinishedEvents: true
language: sv
maxDaysToShow: 2
maxEventCount: 6
name: Kalender
noEventsForNextDaysText: Ingenting kommande dagar
noEventsForTodayText: Ingenting idag
showColors: true
showDate: true
showDescription: false
showFullDayProgress: true
showLoader: true
showLocation: true
showMonth: false
showNoEventsForToday: true
showProgressBar: true
showRelativeTime: true
showWeekDay: true
sortByStartTime: true
timeColor: '#d9b08c'
type: 'custom:atomic-calendar-revive'

```

### Versions

- HomeAssistant Version: 0.114.2
- Plugin Version: v2.1.1
