### ISSUE TITLE
Not possible to set another language

### ISSUE THREAD

**Issue by tomasrudh** [marksie1988/atomic-calendar-revive#278]
- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

Setting Language in the configuration does not change the language.

### Steps to Reproduce

1. In the yaml-file, set language: 'sv'

**Expected behavior**

Week day names should be in Swedish

**Actual behavior:**

Week day names are still in English

**Card Configuration**

```yaml
type: "custom:atomic-calendar-revive"
showColors: true
showWeekDay: true
language: 'sv'
highlightToday: true
eventTitleColor: 'silver'
entities:
- calendar.family
style: |
  .event-title {
    color: var(--primary-text-color);
  }
```

### Versions

- HomeAssistant Version: 0.114.1
- Plugin Version: 2.1.1
