### ISSUE TITLE
All day event is shown on wrong day

### ISSUE THREAD

**Issue by tomasrudh** [marksie1988/atomic-calendar-revive#292]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug
Full day events are shown in the event list even when ended the day before.
### Steps to Reproduce

Create a full day event in the calender for the day before the current day.
**Expected behavior**

The event should not show in the list current days events.
**Actual behavior:**

The event does show in the current day events.
**Screenshots**

**Card Configuration**

```yaml
type: "custom:atomic-calendar-revive"
showColors: true
showWeekDay: true
language: 'sv'
highlightToday: true
eventTitleColor: 'silver'
entities:
- calendar.family
```

### Versions

- HomeAssistant Version: 0.114.4
- Plugin Version: 2.1.1
