### ISSUE TITLE
Language detection fails - defaults to english on german HA installation

### ISSUE THREAD

**Issue by breti** [marksie1988/atomic-calendar-revive#299]
### Prerequisites

- [ X ] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

HA Language detection fails. I've set "Language: German" ("Sprache: Deutsch") in my HA user's settings, the HA GUI is shown in german language, but I have to add "language: de" to Atomic Calendar Revive's configuration to have german texts and date format. 

### Steps to Reproduce

I've added two lovelace cards, settings below. Adding "language: de" is required by at least one of both cards to switch both cards to german language.

**Expected behavior**

Texts in german language

**Actual behavior:**

Texts in english language

**Screenshots**

![grafik](https://user-images.githubusercontent.com/3628895/92637444-20c7a000-f2d9-11ea-918f-720092c65e73.png)

**Card Configuration**

```yaml
disableEventLink: false
disableLocationLink: false
enableModeChange: false
entities:
  - entity: calendar.contacts
fullDayEventText: ''
maxDaysToShow: 7
name: Anstehende Jahrestage
showDescription: false
showLocation: false
showMonth: false
showNoEventsForToday: false
showProgressBar: false
showWeekDay: true
sortByStartTime: false
type: 'custom:atomic-calendar-revive'


dateFormat: LL
disableEventLink: false
disableLocationLink: false
enableModeChange: false
entities:
  - blacklist: 'Urlaub,Krank'
    entity: calendar.mail_jens_bretschneider_de
  - entity: calendar.hackerspace_bremen
    eventCalName: HSHB
  - entity: calendar.hshb_mitglieder
    eventCalName: HSHB
fullDayEventText: Ganztägig
hoursFormat: default
maxDaysToShow: 5
name: Anstehende Termine
noEventsForNextDaysText: Keine Termine in den nächsten Tagen
showCurrentEventLine: false
showDate: false
showDescription: false
showLastCalendarWeek: false
showLocation: false
showMonth: false
showNoEventsForToday: false
showProgressBar: true
showWeekDay: true
sortByStartTime: false
type: 'custom:atomic-calendar-revive'
untilText: bis

```

### Versions

- HomeAssistant Version: 0.114.4
- Plugin Version: v2.2.3
