### ISSUE TITLE
Multiple day events not shown on all days / no duration information for all day events

### ISSUE THREAD

**Issue by noxhirsch** [marksie1988/atomic-calendar-revive#310]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug
I have two multiple day events in my calendar:
- The first one starts today at 10 ends in three days. This one is shown in the calendar only today but tells that it ends in three days. So that part is more like a feature request: It would be nice to have that event shown on all days with the information which day of the total duration it is. E.g. "Eventname (2/5)"
- The second event is a multiple days all day event. It is also only shown today in the calendar and does not have any information that it continues over multiple days. Here it is a bug which could be fixed with the solution above.

### Steps to Reproduce

1. Add event starting today until in three days with start and end time
2. Add event starting today until in three days as all day event

**Expected behavior**
For the bug part: At least also show the end date for all day events
For the feature request part: List the multiple day event on every day with the information which day of the total duration it is. E.g. "Eventname (2/5)"

**Actual behavior:**
Multiple day events are only shown once - all day events with no information about its duration.

**Screenshots**
![image](https://user-images.githubusercontent.com/30938717/93560996-aa373c00-f983-11ea-9517-157f6eacd333.png)

**Card Configuration**

```yaml
type: 'custom:atomic-calendar-revive'
entities:
  - entity: calendar.nico_arbeit
    eventCalName: Nico
maxDaysToShow: 14
maxEventCount: 14
showCurrentEventLine: false
showWeekDay: true
showNoEventsForToday: true
showDescription: false
sortByStartTime: true
showRelativeTime: false
hideFinishedEvents: true
```

### Versions

- HomeAssistant Version: 0.115
- Plugin Version: v2.2.7
