### ISSUE TITLE
Calendar view not showing any events

### ISSUE THREAD

**Issue by Luc3as** [marksie1988/atomic-calendar-revive#324]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of the following:
[ X]   - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
[ X]  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
[ X]  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug
I had configuration with icon types and filters, and it was warking as expected, however after some update it stopped working,  bellow is my actual configuration. I tried to use very simple configuration and it is not showing any events neither. 

![image](https://user-images.githubusercontent.com/6381468/94553440-d2af1800-0258-11eb-91b8-0a5267d54ad1.png)

When switched to event mode there are events in the same calendar . 
![image](https://user-images.githubusercontent.com/6381468/94553494-e195ca80-0258-11eb-879e-de5c30d0a5f8.png)

![image](https://user-images.githubusercontent.com/6381468/94553510-e8bcd880-0258-11eb-94e2-dcb2af5aa039.png)

### Steps to Reproduce

**Expected behavior**

**Actual behavior:**

**Screenshots**

**Card Configuration**

```yaml
entities:
  - entity: calendar.majka_praca
    whitelist: 'Ranná,Poobedná,Celodenná'
    type: 'icon1,icon2,icon3'
    titleColor: red
firstDayOfWeek: 1
maxDaysToShow: 7
name: Majka práca
type: 'custom:atomic-calendar-revive'
calEventIcon1: 'mdi:white-balance-sunny'
calEventIcon1Color: '#ebc400'
calEventIcon1Filter: Ranná
calEventIcon2: 'mdi:food'
calEventIcon2Color: '#359c3c'
calEventIcon2Filter: Poobedná
calEventIcon3: 'mdi:calendar-blank'
calEventIcon3Color: '#1987d1'
calEventIcon3Filter: Celodenná
disableCalEventLink: true
disableCalLocationLink: true
showColors: true
showCurrentEventLine: true
showEventIcon: true
showLastCalendarWeek: true
showLoader: true
showMonth: true
showProgressBar: true
defaultMode: Calendar

```

### Versions

- HomeAssistant Version: 115.4
- Plugin Version: 2.3.2

**Comment by marksie1988** [comment]
Hi @Luc3as 

The icons were changed a few versions back to allow more flexibility. 

```
entities:
  - entity: calendar.majka_praca
    whitelist: 'Ranná'
    Icon: 'mdi:white-balance-sunny'
    color: '#ebc400'
```

You would then add the calendar entity for each icon / filter required. 

This was the best solution to allow as many icons as you like.
