### ISSUE TITLE
All day events not shown on calendar view

### ISSUE THREAD

**Issue by GregoryKowalik** [marksie1988/atomic-calendar-revive#325]
## Summary

Hi, 

I really like your calendar card :) I was playing around many different config options but stuck at some point and I'm not able to display full day events on calendar view whilst I see them in the events view. Can you help me get this working, please?

My card yaml looks like this:

```yaml
type: 'custom:atomic-calendar-revive'
entities:
  - entity: calendar.kalendarz_gmail
    icon: 'mdi:star'
    color: blue
  - entity: calendar.contacts
    icon: 'mdi:gift'
    color: yellow
  - entity: calendar.kalendarz_swiat_nietypowych
    icon: 'mdi:star'
    color: red
name: Kalendarz
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 7
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLocationLink: false
dimFinishedEvents: true
showMonth: true
showCurrentEventLine: true
disableLocationLink: true
showFullDayProgress: true
showProgressBar: false
showWeekDay: true
disableEventLink: true
showNoEventsForToday: true
showEventIcon: false
noEventsForTodayText: Nic na dziś
defaultMode: Calendar
showDate: true
sortByStartTime: true
showLocation: false
showDeclined: true
fullDayEventText: Cały dzień
untilText: do
```
I'm running Home Assistant 0.115.6 and Atomic Calendar Revive 2.3.2

Many thanks!
Greg
