### ISSUE TITLE
Birthday Calendar Doesn't Populate

### ISSUE THREAD

**Issue by StuDaBaiker** [marksie1988/atomic-calendar-revive#334]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

Birthday calendars are not populated in calendar or event view.

### Steps to Reproduce

1. N/A

**Expected behavior**
Have added three calendars. Holidays and personal calendar are functioning correctly. Birthday calendar does not appear in calendar view or event view.

**Actual behavior:**

Birthday calendar does not appear in calendar view or event view. Screenshot shows built in calendar (functioning correctly) and atomic calendar for comparison. Have set max results to 500 but still doesn't show.

**Screenshots**
https://imgur.com/a/FJPT0Ku

**Card Configuration**

```yaml
  type: 'custom:atomic-calendar-revive'
  name: Calendar Card
  enableModeChange: true
  firstDayOfWeek: 1
  maxDaysToShow: 7
  entities:
    - entity: calendar.stu_calendar
      icon: 'mdi:calendar-blank'
    - entity: calendar.birthdays
      icon: 'mdi:birthday'
    - entity: calendar.holidays_in_canada
      icon: 'mdi:palm-tree'
  dimFinishedEvents: true
  showLoader: true
  showDate: false
  sortByStartTime: true
  hideFinishedEvents: false
  showRelativeTime: false
  defaultMode: Calendar
```

### Versions

- HomeAssistant Version: 0.116.4
- Plugin Version: v2.5.1
