### ISSUE TITLE
The calendar can't be loaded from Home Assistant component issue

### ISSUE THREAD

**Issue by tpbillund** [marksie1988/atomic-calendar-revive#343]
## Summary

From one day to another, my calendar was working and then "The calendar can't be loaded from Home Assistant component".
I have installed the newest atomic-calendar-revive and it has worked fine.

HassOI is version 1.6.1
HomeAssistant is version 0.117.1

**Expected behavior**

Showing the calendar event and month calendar

**Actual behavior:**

Month calendar is missing icons and the event calendar is showing "The calendar can't be loaded from Home Assistant component".

**Screenshots**

**Card Configuration**

The code in my ui-lovelace.yaml file is, and again was working fine and haven't added new code or something else..

```
.....
            cards:
              - type: "custom:atomic-calendar-revive"
                style: |
                  ha-card {
                  }
                  .card-content {
                    padding: 0 0 0 0px;
                    box-shadow: none;
                  }
                enableModeChange: true
                defaultMode: Calendar
                dateFormat: L
                maxDaysToShow: 30
                firstDayOfWeek: 1
                sortByStartTime: true
                showDescription: true
                showNoEventsForToday: true
                entities:
                  - entity: calendar.fodselsdag
                    icon: 'mdi:flag-variant'
                    color: red
                  - entity: calendar.aktiviteter
                    icon: 'mdi:circle-edit-outline'
                    color: '#FF3898'
                  - entity: calendar.helligdage_i_danmark
                    icon: 'mdi:home'
                    color: orange
.....
.....
            cards:
              - type: 'custom:atomic-calendar-revive'
                name: Aktiviteter
                entities:
                  - entity: calendar.fodselsdag
                  - entity: calendar.aktiviteter
                  - entity: calendar.helligdage_i_danmark
                fullDayEventText: Hele dagen!
                untilText: Until
                defaultMode: Event
                enableModeChange: true
                showColors: true
                maxDaysToShow: 60
                maxEventCount: 0
                showLocation: true
                showMonth: true
                showWeekDay: true
                firstDayOfWeek: 1
                disableEventLink: true
                disableLocationLink: true
                showCurrentEventLine: false
                dateColor: '#ffffff'
                dateSize: 90
                timeColor: '#cccccc'
                timeSize: 80
                titleColor: '#ffffff'
                titleSize: 100
                locationIconColor: 'rgb(230, 124, 115)'
                locationLinkColor: '#BBBBBB'
                locationTextSize: 90
                dimFinishedEvents: true
                finishedEventOpacity: 0.3
                finishedEventFilter: grayscale(100%)
                dayWrapperLineColor: '#999999'
                eventBarColor: '#aaaaaa'
                showProgressBar: true
                progressBarColor: '#aaaaaa'
                showFullDayProgress: true
                noEventsForTodayText: Ingen aktiviteter idag
                noEventsForNextDaysText: Ingen aktiviteter de næste dage
                showRelativeTime: true
                showEventIcon: false
.....
```

## Additional context

Non
