### ISSUE TITLE
Weekdays and relative times are not displayed in the configured language

### ISSUE THREAD

**Issue by bennierex** [marksie1988/atomic-calendar-revive#344]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

Weekdays and relative times are not displayed in the language that is set in the configuration. Setting the language for either the user and/or in the card config doesn't make a difference.

### Steps to Reproduce

See configuration and screenshots below.

**Expected behavior**

Weekdays and relative times displayed in the configured language.

**Actual behavior:**

Weekdays and relative times are displayed in English.

**Screenshots**

<img src="https://user-images.githubusercontent.com/6532813/98043142-087d8880-1e25-11eb-8472-60454d28d497.png" width="400px" />

**Card Configuration**

```yaml
entities:
  - color: white
    entity: calendar.family
  - color: yellow
    entity: calendar.xxxxxx
  - color: blue
    entity: calendar.zzzzz
  - color: green
    entity: calendar.yyyyyy
  - color: orange
    entity: calendar.wwwww
  - color: grey
    entity: calendar.verjaardagen
language: nl-NL
type: 'custom:atomic-calendar-revive'
firstDayOfWeek: 1
maxDaysToShow: 7
refreshInterval: 60
showDate: false
showRelativeTime: true
showLocation: false
untilText: tot
fullDayEventText: Hele dag
noEventsForNextDaysText: Geen afspraken komende dagen
noEventsForTodayText: Geen afspraken vandaag
showWeekDay: true
dateFormat: LL
```

### Versions

- HomeAssistant Version: 0.117.1
- Plugin Version: 2.5.1

### Additional Information

Let me know if you need more info.
