### ISSUE TITLE
Long description problem

### ISSUE THREAD

**Issue by DunklerPhoenix** [marksie1988/atomic-calendar-revive#346]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

A long description of an event let "explode" the view :D

**Screenshots**

![EXDdGXsnfF](https://user-images.githubusercontent.com/1261305/99000331-62730200-2539-11eb-8b50-7934973e3365.png)
    

**Card Configuration**

```
type: 'custom:atomic-calendar-revive'
name: Entsorgungskalender
enableModeChange: true
defaultMode: Calendar
entities:
  - entity: calendar.entsorgungskalender
    icon: 'mdi:delete-empty'
    color: green
calShowDescription: true
showLastCalendarWeek: true
disableCalEventLink: true
disableCalLocationLink: true
showWeekDay: true
firstDayOfWeek: 1
maxDaysToShow: 30
showDate: false
showDeclined: false
hideFinishedEvents: false
showRelativeTime: false
showLocation: true
sortByStartTime: false
showFullDayProgress: true
showEventIcon: true
disableEventLink: true
```

### Versions

- HomeAssistant Version: 0.116.0
- Plugin Version: 2.5.1
