### ISSUE TITLE
Progress Bar does not show status correctly

### ISSUE THREAD

**Issue by noname-ever** [marksie1988/atomic-calendar-revive#350]
### Prerequisites

- [ X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug
The "showProgressBar" option only shows blue line and "progressBarColor" also have no effect to its color.

### Steps to Reproduce

1.  Install newest version of HA.
2.  Install newest version of ACR.
3.  Create new ACR card using my config.

**Expected behavior**
Circle is show over line to represent current status of an event.

**Actual behavior:**
NO circle is show over line to represent current status of an event.

**Screenshots**
![image](https://user-images.githubusercontent.com/60624891/100153567-f7b4b580-2eac-11eb-9f22-c40af18792a3.png)

**Card Configuration**

```
type: 'custom:atomic-calendar-revive'
name: Įvykiai
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 31
entities:
  - entity: calendar.holidays_in_lithuania
    icon: 'hass:flag-variant'
    color: red
  - entity: calendar.gimtadienis
    icon: 'hass:cake-variant'
    color: yellow
  - entity: calendar.masina
    icon: 'hass:car-sports'
    color: white
refreshInterval: 60
dateFormat: 'dddd, MMMM D'
showDate: true
europeanDate: false
sortByStartTime: true
showRelativeTime: true
defaultMode: Event
linkTarget: _blank
maxEventCount: 5
showLocation: true
showMonth: true
showWeekDay: true
showEventIcon: true
language: lt
hoursFormat: 'HH:MM'
showLoader: true
calShowDescription: true
showDescription: true
showProgressBar: true


```

### Versions

- HomeAssistant Version: 0.118.3
- Plugin Version: 2.5.1
