### ISSUE TITLE
Highlight today

### ISSUE THREAD

**Issue by manuelo1983** [marksie1988/atomic-calendar-revive#361]
### Describe the bug
I have the problem that I would like to highlight the current day in color, but unfortunately this does not work. I have card mod active and with the calendar title it also works, but just not with the current day.

**Card Configuration**

nameColor: "rgb(119,221,119)" this function e.g. is working fine, but the function for highlighting the actual day is not working.

```
type: vertical-stack
cards:
  - dateBottomFormat: dd
    disableLinks: false
    endText: Ende
    entities:
      - entity: calendar.contacts
        name: Contacts
      - entity: cxxx
        name: xxx
    eventsLimit: 5
    maxEventCount: 8
    europeanDate: true
    fullDayEventText: Ganztags
    hardLimit: true
    hideDeclined: false
    hideHeader: false
    hidePastEvents: true
    hideTime: false
    highlightToday: true
    ignoreEventsByLocationExpression: ''
    ignoreEventsExpression: ''
    maxHeight: false
    notifyDateTimeFormat: 'MM/DD/YYYY HH:mma'
    notifyEntity: ''
    numberOfDays: '30'
    progressBar: false
    removeFromEventTitle: ''
    showEventOrigin: false
    showLocation: true
    showLocationIcon: true
    showMultiDay: true
    startFromToday: true
    startText: Start
    timeFormat: 'HH:mm'
    title: Familienkalender
    type: 'custom:atomic-calendar-revive'
    useSourceUrl: false
    firstDayOfWeek: 1
    maxDaysToShow: 30
    dateFormat: 'D.M.YYYY HH:mm'
    defaultMode: Event
    linkTarget: _blank
    calShowDescription: false
    name: Familienkalender
    showDeclined: false
    hideFinishedEvents: true
    showRelativeTime: false
    sortByStartTime: true
    showDate: true
    untilText: bis
    showCurrentEventLine: false
    showMonth: true
    showWeekDay: true
    disableEventLink: false
    showNoEventsForToday: false
    noEventsForNextDaysText: null
    noEventsForTodayText: null
    showEventIcon: false
    showFullDayProgress: false
    showLastCalendarWeek: false
    dimFinishedEvents: true
    showProgressBar: true
    disableCalLocationLink: false
    disableCalEventLink: false
    showLoader: true
    hoursFormat: 'HH:mm'
    refreshInterval: 1200
    nameColor: 'rgb(119,221,119)'
    calDayColor: 'rgb(119,221,119)'
  - type: 'custom:gap-card'
```

### Versions

- HomeAssistant Version: 2020.12.7
- Plugin Version: v2.5.5
