### ISSUE TITLE
No icons (or event text of any kind) in Calendar mode using caldav integration

### ISSUE THREAD

**Issue by mainmachine** [marksie1988/atomic-calendar-revive#392]
I'm using the caldav integration pointing to a Nextcloud instance which works in HA's calendar, shows all four of the calendars I've defined, and works in the Event view.

## Expected behaviour
I would expect to see icons on days where events exist in the Calendar mode.

## Current behaviour
I do not see any indication of any events in the Calendar mode.

## Screenshot
![Screenshot from 2021-01-25 11-19-18](https://user-images.githubusercontent.com/12385366/105733227-4efff200-5eff-11eb-84d7-d4a360040f2f.png)
On the left is the HA calendar card for reference. As you can see, events are indicated here, but not on the atomic-calendar-revive card.

## Possible reasons and solutions
As noted [here](https://marksie1988.github.io/atomic-calendar-revive/quickstart.html#more-than-5) even with the google-calendar integration, extra configuration is required to show more than 5 events. The configuration options for google calendar and caldav are different, so it's possible that atomic calendar revive is looking for a parameter that is missing from the caldav integration. This is speculation, of course. :)

## Steps to reproduce
Add a caldav calendar in configuration.yaml like this:

```
calendar:
  - platform: caldav
    days: 45
    username: !secret nc_user
    password: !secret nc_pw
    url: !secret nc_url
```

With this configuration, available calendars are detected and added automatically. If the developers do not have access to a working caldav calendar, I would be happy to create a dummy calendar and temporary credentials on my server to facilitate resolving this issue. 

## Your environment
Running a Supervised instance of the latest HA 2021.1.5 on x86 hardware on Ubuntu 18.04 LTS. I have been running the same instance for about a year, upgrade regularly and have significant experience as a Linux system administrator and software engineer. I run a tight ship and RTFM regularly. :)

## Checklist
- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [ ] I am mostly sure that the problem is related to the code and isn't my fault.

Please let me know what else I can do to help get this sorted - I love the card and would love to use it to help my family plan their day!

**Comment by marksie1988** [comment]
Please could you provide a copy of your configuration? 

This will help me see the issue, looking at this i think that the option 

```yml
icon: mdi-badge
```

**Comment by mainmachine** [comment]
I am setting icons for each calendar, however I'm using the `mdi:*` format. I tried `icon: mdi-badge` as in your question, but that did not change anything.

Here is my config, I've changed the calendar names to obfuscate personal data:

```
defaultMode: Event
disableLocationLink: true
enableModeChange: true
entities:
  - entity: calendar.user1
    color: '#ffa500'
    icon: 'mdi:star'
  - entity: calendar.user2
    color: '#9c169c'
    icon: 'mdi:gender-female'
  - entity: calendar.user3
    color: '#c743ff'
    icon: 'mdi:google-downasaur'
  - entity: calendar.user4
    color: '#ff69b4'
    icon: 'mdi:heart'
name: When to do the Things
showColors: true
showDate: true
showLoader: true
showMonth: false
sortByStartTime: false
type: 'custom:atomic-calendar-revive'
firstDayOfWeek: 1
maxDaysToShow: 7
dimFinishedEvents: true
```
