### ISSUE TITLE
Not working with Nextcloud CalDAV

### ISSUE THREAD

**Issue by ami6de** [marksie1988/atomic-calendar-revive#469]
## Expected behaviour

As Nextcloud calendars can be integrated into HA, I'd expect that with the definition of calendars in e.g. configuration.yaml, a calendar should be visible, too.

## Current behaviour

Error message: "The calendar can't be loaded from Home Assistant component. See Here"

## Steps to reproduce

configuration.yaml:

```
calendar:
  - platform: caldav
    username: xxx
   password: !secret caldav
    url: https://IPaddress/remote.php/dav
    calendars:
      - mycalendarname
```

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Hi There, 

Please could you supply the configuration for the Atomic Calendar Revive card? 

without this I would be unable to troubleshoot the issue.

**Comment by ami6de** [comment]
I tried several variants:

```
resources:
  - url: /local/community/atomic-calendar-revive/atomic-calendar-revive.js
    type: module
type: custom:atomic-calendar-revive
name: Familien-Kalender
enableModeChange: true
calShowDescription: true
showLastCalendarWeek: true
firstDayOfWeek: 1
maxDaysToShow: 7
showDate: true
entities:
  - entity: familie
```

**Comment by marksie1988** [comment]
Ok, resources should now be added by the UI rather than via the configuration.yaml file, however that shouldn't be the issue, i can tell from the error that the card is loading its just an issue with the configuration. try this configuration, assuming that the entity in your HA for the calendar is `caneldar.familie` this should work: 

```
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.familie
    icon: mdi:home-heart
    color: rgb(170,0,0)
name: Familien-Kalender
enableModeChange: true
calShowDescription: true
showLastCalendarWeek: true
firstDayOfWeek: 1
maxDaysToShow: 7
showDate: true
```

the main things here are: 
- an icon must be used to see the event on the calendar mode (not required if only using events mode)
- the entity, must be the calendar entity as it is shown in the HA entities section, this can be checked under the developer tools, states tab you will get a "entity" dropdown which should have your calendar listed

if all of the above is correct then it should work.
