### ISSUE TITLE
[BUG] Show future events

### ISSUE THREAD

**Issue by SeLLeRoNe** [marksie1988/atomic-calendar-revive#98]
**Describe the bug**
I am not sure it's a bug or it is actually not present, but I would like to be able to see in the calendar future events, with the ability on click on the date with an event and have information about that (maybe some bar that expand below the calendar itself?)

**To Reproduce**
Steps to reproduce the behavior.
- Have a calendar with future events configured

**Expected behavior**
I would expect to see a dot (or any graphical sign) on a day in the future where events are present (technically also in the past, but that would be a plus :D )

**Screenshots**
![image](https://user-images.githubusercontent.com/9599441/81729680-a737b680-948c-11ea-9d7d-e3dfd616c3f2.png)

**Setup Information (please complete the following information):**
 - Plugin Version 1.4.1
 - Browser & Version [e.g. chrome, safari, chrome mobile etc.]
Chrome  (81.0.4044.138) on Windows 10

**Additional context**
I am using CalDAV and ICS calendars, not Google, not sure it might be relevant!

**Comment by SeLLeRoNe** [comment]
Oh, I forgot my config, it might be useful :D

```
      - type: custom:atomic-calendar-revive
        name: Calendar
        enableModeChange: true
        defaultMode: 2
        dateFormat: L
        maxDaysToShow: 30
        startDaysAhead: 30
        maxEventCount: 0
        sortByStartTime: true
        showDescription: true
        showLoader: true
        showColors: true
        showDate: true
        CalEventHolidayColor: lime
        CalEventIcon1Filter: events
        CalEventIcon2Filter: birthday
        CalEventIcon1Filter: birthday
        CalEventIcon2Filter: waste,bills
        entities:
          - entity: calendar.personal_andrea
#            type: icon2
          - entity: calendar.uk_holidays
            type: holiday
```

**Comment by marksie1988** [comment]
Hi @SeLLeRoNe 

by adding `type:` to the entity you should see an icon under the date that an event occurs on, then when you click on one of the days with an event it will be displayed underneeth the calendar: 

![image](https://user-images.githubusercontent.com/159166/81816562-68087480-9523-11ea-99c6-255599cd2097.png)

I am looking at adding more details to the item list at the bottom, however the data isn't pushed there yet so needs re-working.

**Comment by marksie1988** [comment]
On doing further testing, i believe that the issue is with the icon filters. 

Your icon filter is removing the events that dont match that filter and thus leaving you with no events on the calendar.

**Comment by SeLLeRoNe** [comment]
Hi there,
thanks for your responses :)

I did cleanup my config and now looks like this:
```
      - type: custom:atomic-calendar-revive
        name: Calendar
        enableModeChange: true
        defaultMode: 2
        dateFormat: L
        maxEventCount: 0
        sortByStartTime: true
        showDescription: true
        showLoader: true
        showColors: true
        showDate: true
        entities:
          - entity: calendar.personal_andrea
          - entity: calendar.uk_holidays

```

But the result is still the same:
![image](https://user-images.githubusercontent.com/9599441/81835126-26d38d00-9542-11ea-81ea-78b35d1326ef.png)


Do you see something clearly wrong?
I also removed the "type" from the entity (my idea is that was the icon assigned to the calendar buyt maybe not)
I have tried to remove all unnecessary configurations, I doubt the one I left might have an impact

Do you see any obvious reason for it not to show the event on the 25th?

Thanks

**Comment by marksie1988** [comment]
Hi,

So at the moment you must have the `type` set under the entity in order for the event to be listed. 

For example if you add `type: icon1` to one of the calendars that has an event it will show an icon on the date it occurs. 

If you select that date it should list the event name under the calendar. 

Im hoping to rewrite the way this works in the future but I'm still getting my head around how the card works, along with learning JS as I go. 

My vision is that when you click the date in theory you can show any information from an event that you want to. But Im figuring out how to do that at the moment :)

**Comment by SeLLeRoNe** [comment]
Hi,
Ok, I have added type back but that doesn't change a thing.
I also  added "showNoEventsForToday: true" but it doesn't even show the message on today view...

The ideas to improve this card and provide more functionality can be a very interesting thing :)

I just hope I'll manage to have it working and start from there with feedback and ideas :)

**Comment by marksie1988** [comment]
So i have only used this card with Google Calendar, im not sure if that is whats causing your issue, however when I do the same configuration on v1.4.1 it works without issue: 

![image](https://user-images.githubusercontent.com/159166/81934363-c2b6d480-95e6-11ea-80fb-4f2042f7c9a8.png)

```yaml
name: Calendar
enableModeChange: true
defaultMode: 2
dateFormat: L
maxDaysToShow: 30
sortByStartTime: true
showDescription: true
showNoEventsForToday: true
type: 'custom:atomic-calendar-revive'
entities:
  - entity: calendar.personal_andrea
    type: icon1
  - entity: calendar.uk_holidays
    type: icon2
```
